# Site settings
baseURL = "https://allalen.com"
languageCode = "en-US"
title = "Alla Len"
theme = "hugo-split-theme"



# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = "G-5TG9QDRC0P"

# Copyright
copyright = "&copy;2024 Alla Len"

[params]

  # Metadata for search engines and social sharing
  name = "Alla Len"
  description = "Step into Alla Len's realm of pop-soul melodies, where each note played on the piano and each lyric sung is a whisper from the soul. Inspired by the evocative works of Adele, Evanescence, and Alicia Keys, her songs echo from the depths of heartache to the heights of love's promises. In I Cannot Forget You experience the haunting ache of love unrequited. Feel destiny's pull in Stay with Me Forever and embark on romantic escapades in Love sur la Garonne. Alla Len's music, deeply introspective yet universally resonant, takes you on an emotional journey with the transformative power of love as your guide. Immerse yourself."
  shareImage = "images/social.jpg"
  twitterHandle = "#"

  # Favicon
  favicon = "favicon.ico"

  # Section - Content
  [params.content]
    name = "Alla Len"
    tagline = "Songwriter. Singer. Pianist."
    bio = "A tapestry of sound, woven with the threads of love and longing. My songs are bridges to distant souls, rivers of emotions that unite and divide. Each note, a quiet plea; each lyric, a poetic testament. Here, the heart finds its voice in the ethereal. Immerse yourself."

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = false
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = true             # Must be set to true to display the video
      youtubeId = "RW5TOWyEtyY" # The YouTube video ID for embedding
      mute = false              # Set to false if you want sound


  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Email"
        url = "#"

      [[params.links.list1.link]]
        text = "Facebook"
        url = "#"

      [[params.links.list1.link]]
        text = "Newsletter"
        url = "#"

      [[params.links.list1.link]]
        text = "Newsletter"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "YouTube"
        url = "#"

      [[params.links.list2.link]]
        text = "TikTok"
        url = "#"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Support me"

      [[params.links.list3.link]]
        text = "Patreon"
        url = "#"

      [[params.links.list3.link]]
        text = "Buy Me a Coffee"
        url = "#"

      [[params.links.list3.link]]
        text = "Boosty"
        url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
